local M = {}
--- Diagnostic severities.
M.diagnostics = {
	ERROR = "",
	WARN = "",
	HINT = "",
	INFO = "",
}

M.dap = {
	Breakpoint = "◉",
    BreakpointStopped = "◌",
    BreakpointCondition = "◍",
    BreakpointRejected = "⊗",
    BreakpointLog = "⌽"
}

M.ui = {
	ArrowCircleDown = "",
	ArrowCircleLeft = "",
	ArrowCircleRight = "",
	ArrowCircleUp = "",
	BoldArrowDown = "",
	BoldArrowLeft = "",
	BoldArrowRight = "",
	BoldArrowUp = "",
	BoldClose = "",
	BoldDividerLeft = "",
	BoldDividerRight = "",
	BoldLineLeft = "▎",
	BoldLineMiddle = "┃",
	BoldLineDashedMiddle = "┋",
	BookMark = "",
	BoxChecked = " ",
	Bug = " ",
	Stacks = "",
	Scopes = "",
	Watches = "󰂥",
	DebugConsole = " ",
	Calendar = " ",
	Check = "",
	ChevronRight = "",
	ChevronShortDown = "",
	ChevronShortLeft = "",
	ChevronShortRight = "",
	ChevronShortUp = "",
	Circle = " ",
	Close = "󰅖",
	CloudDownload = " ",
	Code = "",
	Comment = "",
	Dashboard = "",
	DividerLeft = "",
	DividerRight = "",
	DoubleChevronRight = "»",
	Ellipsis = "",
	EmptyFolder = " ",
	EmptyFolderOpen = " ",
	File = " ",
	FileSymlink = "",
	Files = " ",
	FindFile = "󰈞",
	FindText = "󰊄",
	Fire = "",
	Folder = "󰉋 ",
	FolderOpen = " ",
	FolderSymlink = " ",
	Forward = " ",
	Gear = " ",
	History = " ",
	Lightbulb = " ",
	LineLeft = "▏",
	LineMiddle = "│",
	List = " ",
	Lock = " ",
	NewFile = " ",
	Note = " ",
	Package = " ",
	Pencil = "󰏫 ",
	Plus = " ",
	Project = " ",
	Search = " ",
	SignIn = " ",
	SignOut = " ",
	Tab = "󰌒 ",
	Table = " ",
	Target = "󰀘 ",
	Telescope = " ",
	Text = " ",
	Tree = "",
	Triangle = "󰐊",
	TriangleShortArrowDown = "",
	TriangleShortArrowLeft = "",
	TriangleShortArrowRight = "",
	TriangleShortArrowUp = "",
}

M.misc = {
	Robot = "󰚩 ",
	Squirrel = " ",
	Tag = " ",
	Watch = "",
	Smiley = " ",
	Package = " ",
	CircuitBoard = " ",
}

return M
